name: Continuous Delivery of Python package

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  workflow_dispatch:
    inputs:
      production_release:
        description: "Production release?"
        type: boolean
        required: true
        default: true
      bump_major:
        description: "Bump major version?"
        type: boolean
        required: false
        default: false
      specific_version:
        description: "Specific version to set (leave empty for automatic versioning)"
        type: string
        required: false
        default: ""

concurrency: release

permissions:
  contents: write
  packages: read

jobs:
  ci-check-python:
    name: Check Python
    uses: ./.github/workflows/check-python.yaml

  ci-build-python:
    name: Build Python
    uses: ./.github/workflows/build-python.yaml
    needs: ci-check-python

  release:
    name: Release Library
    needs: ci-build-python
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch entire repository history so we can determine version number from it
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Get branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: get_branch

      - name: Set Git user as GitHub actions
        run: git config --global user.email "actions@github.com" && git config --global user.name "github-actions"

      - name: Create Continuous Deployment - Beta (non-prod)
        if: steps.get_branch.outputs.branch == 'main' && !inputs.production_release
        run: |
          RELEASE_ARGS="--prerelease --define=branch=main"

          if [[ "${{ inputs.bump_major }}" == "true" ]]; then
            RELEASE_ARGS="$RELEASE_ARGS --define=force_level=major"
          fi

          if [[ -n "${{ inputs.specific_version }}" ]]; then
            RELEASE_ARGS="$RELEASE_ARGS --define=next_version=${{ inputs.specific_version }}"
          fi
          echo "Release args: $RELEASE_ARGS"
          poetry run semantic-release -v DEBUG $RELEASE_ARGS publish
          gh release edit --prerelease "v$(poetry run semantic-release print-version --current)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Continuous Deployment - Production
        if: steps.get_branch.outputs.branch == 'main' && inputs.production_release
        run: |
          RELEASE_ARGS="--define=version_source=commit --define=patch_without_tag=true --define=branch=main"

          if [[ "${{ inputs.bump_major }}" == "true" ]]; then
            # Make sure force_level is properly applied for major version bumps
            RELEASE_ARGS="$RELEASE_ARGS --define=force_level=major --define=major_on_zero=true"
          fi

          if [[ -n "${{ inputs.specific_version }}" ]]; then
            RELEASE_ARGS="$RELEASE_ARGS --define=next_version=${{ inputs.specific_version }}"
          fi
          echo "Release args: $RELEASE_ARGS"
          poetry run semantic-release -v DEBUG $RELEASE_ARGS publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish package distributions to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
